---
title: "Week2_Leaflet"
author: "Yun Yao"
date: "May 8, 2019"
output: html_document
---

## Your First Map
```{r, eval=FALSE}
library(leaflet)
my_map <- leaflet() %>%
    addTiles()
my_map

# equivalent
library(leaflet)
my_map = leaflet()
my_map = addTiles(my_map)
my_map
```

## Adding Markers
```{r, eval=FALSE}
library(leaflet)
my_map <- my_map %>%
    addMarkers(lat = 39.2980803, lng = -76.5898801, popup = "Jeff Leek's Office")
my_map

# equivalent
my_map = addMarkers(my_map, lat = 39.2980803, lng = -76.5898801, 
                    popup = "Jeff Leek's Office")
my_map
```

```{r, eval=FALSE}
# chaining
library(leaflet)
my_map <- leaflet() %>%
    addTiles() %>%
    addMarkers(lat = 39.2980803, lng = -76.5898801, popup = "Jeff Leek's Office")
my_map
```

## Adding Many Markers
```{r, eval=FALSE}
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),
                 lng = runif(20, min = -76.6, max = -76.5))
head(df)

# pass the data frame to leaflet
df %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers()
```

## Making Custom Markers and Separate Pop-ups
```{r, echo=FALSE}
library(leaflet)
hopkinsIcon <- makeIcon(
    iconUrl = "shield.png",
    iconWidth = 20, iconHeight = 20)
hopkinsIcon

hopkinsLatLong <- data.frame(
    lat = c(39.2973166, 39.3288851, 39.2906617, 39.2970681, 39.2824806),
    lng = c(-76.5929798, -76.6206598, -76.5469683, -76.6150537, -76.6016766))

hopkinsLatLong %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(icon = hopkinsIcon)
```

## Add building names and URLs
```{r, echo=FALSE}
hopkinsSites <- c(
    "<a href = 'http://www.jhsph.edu/'>East Baltimore Campus</a>",
    "<a href = 'https://apply.jhu.edu/visit/homewood/ '>Homewood Campus</a>",
    "<a href = 'http://www.hopkinsmedicine.org/johns_hopkins_bayview/'>Bayview Medical Center</a>",
    "<a href = 'http://www.peabody.jhu.edu/'>Peabody Institute</a>",
    "<a href = 'http://carey.jhu.edu/'>Carey Business School</a>"
)

hopkinsLatLong %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(icon = hopkinsIcon, popup = hopkinsSites)
```

## Mapping Clusters
```{r, echo=FALSE}
df <- data.frame(lat = runif(500, min = 39.25, max = 39.35),
                 lng = runif(500, min = -76.65, max = -76.55))

df %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(clusterOptions = markerClusterOptions())
```

## Mapping Circle Markers
```{r, echo=FALSE}
df <- data.frame(lat = runif(20, min = 39.25, max = 39.35),
                 lng = runif(20, min = -76.65, max = -76.55))

df %>%
    leaflet() %>%
    addTiles() %>%
    addCircleMarkers()
```

## Drawing Circles
```{r, eval=FALSE}
md_cities <- data.frame(name = c("Baltimore", "Frederick", "Rockville", 
                                 "Gaithersburg", "Bowie", "Hagerstown", 
                                 "Annapolis", "College Park", "Salisbury", "Laurel"), 
                                 pop = c(619493, 66169, 62334, 
                                         61045, 55232, 39890, 
                                         38880, 30587, 30484, 25346), 
                                 lat = c(39.2920592, 39.4143921, 39.0840, 
                                         39.1434, 39.0068, 39.6418, 
                                         38.9784, 38.9897, 38.3607, 39.0993),
                                 lng = c(-76.6077852, -77.4204875, -77.1528, 
                                         -77.2014, -76.7791, -77.7200, 
                                         -76.4922, -76.9378, -75.5994, -76.8483))

md_cities %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 1, radius = sqrt(md_cities$pop) * 30)
```

## Drawing Rectangles
```{r, eval=FALSE}
leaflet() %>%
    addTiles() %>%
    addRectangles(lat1 = 37.3858, lng1 = -122.0595,
                  lat2 = 37.3890, lng2 = -122.0625)
```

## Drawing Legends
```{r, echo = FALSE}
df <- data.frame(lat = runif(20, min = 39.25, max = 39.35),
                 lng = runif(20, min = -76.65, max = -76.55),
                 col = sample(c("red", "blue", "green"), 20, replace = TRUE),
                 stringsAsFactors = FALSE)
head(df)

df %>%
    leaflet() %>%
    addTiles() %>%
    addCircleMarkers(color = df$col) %>%
    addLegend(labels = LETTERS[1:3], colors = c("blue", "red", "green"))
```


